// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: user.proto

package server

import (
	"context"

	"zero-demo/user-rpc/internal/logic"
	"zero-demo/user-rpc/internal/svc"
	"zero-demo/user-rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 定义一个 SayHello 一元 rpc 方法，请求体和响应体必填。
func (s *UserServer) SayHello(ctx context.Context, in *pb.SayHelloReq) (*pb.SayHelloResp, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
