// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type UpdateReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdateResp struct {
	Success int64 `json:"success"`
}
